language: python

#Jinja doesn't support Python 3.2 or lower (http://jinja.pocoo.org/docs/dev/intro/#experimental-python-3-support)
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"

install:
  - "pip install ."

script:
  - "roboclone https://github.com/Team4761/2015-Robot-Code.git"